MODULE PARKIND1
  IMPLICIT NONE
  
  INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
  INTEGER, PARAMETER :: JPRM = SELECTED_REAL_KIND(6,37)
  INTEGER, PARAMETER :: JPRD = SELECTED_REAL_KIND(13,300)
  INTEGER, PARAMETER :: JPRB = JPRD
END MODULE

