MODULE PARKIND1
  IMPLICIT NONE
  
  INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
  INTEGER, PARAMETER :: JPRB = SELECTED_REAL_KIND(13,300)
  INTEGER, PARAMETER :: JPRM = JPRB!SELECTED_REAL_KIND(6,37)
END MODULE