MODULE YONOGWDNN
  USE PARKIND1
  IMPLICIT NONE
  
  REAL(KIND=JPRM), ALLOCATABLE :: INPUT(:,:)    ! Input layer NWIDTH * NINP
  REAL(KIND=JPRM), ALLOCATABLE :: HIDDEN(:,:,:) ! NWIDTH * NWIDTH * NHIDDEN
  REAL(KIND=JPRM), ALLOCATABLE :: OUTPUT(:,:)   ! NOUT * NWIDTH

  REAL(KIND=JPRM), ALLOCATABLE :: INPUT_B(:)    ! Input layer bias NWIDTH
  REAL(KIND=JPRM), ALLOCATABLE :: HIDDEN_B(:,:) ! NWIDTH * NHIDDEN
  REAL(KIND=JPRM), ALLOCATABLE :: OUTPUT_B(:) ! NOUT

  INTEGER, PARAMETER :: NINP    = 5
  INTEGER, PARAMETER :: NWIDTH  = 3
  INTEGER, PARAMETER :: NHIDDEN = 6
  INTEGER, PARAMETER :: NOUT    = 5
  
  LOGICAL, PARAMETER :: LLRELU = .FALSE.
  LOGICAL, PARAMETER :: LSELU = .FALSE.
  LOGICAL, PARAMETER :: LTANH = .TRUE.
  
END MODULE YONOGWDNN